-- Seed: Palm Haven rooms, guests, reservations, reservation_guests, room_notes (synthetic)
-- Target hotel (tenant): Palm Haven Hotel

-- Ensure target hotel exists
INSERT INTO public.hotels (name) VALUES ('Palm Haven Hotel') ON CONFLICT (name) DO NOTHING;

-- Seed required hotel-scoped reference data
-- - shifts (AM/PM/Night)
-- - consumables (for consumptions / billing flows)
WITH h AS (
  SELECT id AS hotel_id
  FROM public.hotels
  WHERE name = 'Palm Haven Hotel'
  LIMIT 1
),
shift_rows(name, start_time, end_time) AS (
  VALUES
    ('AM', '06:00'::time, '14:00'::time),
    ('PM', '14:00'::time, '22:00'::time),
    ('Night', '22:00'::time, '06:00'::time)
)
INSERT INTO public.shifts (hotel_id, name, start_time, end_time)
SELECT h.hotel_id, sr.name, sr.start_time, sr.end_time
FROM h
CROSS JOIN shift_rows sr
WHERE NOT EXISTS (
  SELECT 1
  FROM public.shifts s
  WHERE s.hotel_id = h.hotel_id
    AND s.name ILIKE sr.name
);

WITH h AS (
  SELECT id AS hotel_id
  FROM public.hotels
  WHERE name = 'Palm Haven Hotel'
  LIMIT 1
),
consumable_rows(name, category, unit_price, billable) AS (
  VALUES
    ('Mini Bar - Water', 'mini_bar', 5.00::numeric, true),
    ('Mini Bar - Coke', 'mini_bar', 4.00::numeric, true),
    ('Laundry - Shirt', 'laundry', 8.00::numeric, true),
    ('Towels - Extra', 'towels', 0::numeric, false)
)
INSERT INTO public.consumables (hotel_id, name, category, unit_price, billable)
SELECT h.hotel_id, cr.name, cr.category, cr.unit_price, cr.billable
FROM h
CROSS JOIN consumable_rows cr
WHERE NOT EXISTS (
  SELECT 1
  FROM public.consumables c
  WHERE c.hotel_id = h.hotel_id
    AND c.name = cr.name
    AND c.category = cr.category
);

-- Ensure required columns exist (older dev DBs)
ALTER TABLE public.rooms ADD COLUMN IF NOT EXISTS house_keeping_status TEXT;
ALTER TABLE public.reservations ADD COLUMN IF NOT EXISTS promised_time TIME;
CREATE INDEX IF NOT EXISTS idx_rooms_house_keeping_status ON public.rooms(house_keeping_status);

-- 1. ROOMS
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('101', 'RO1KY', 87, 'no_linen', 'normal', false, NULL, 'InProgress', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('102', 'R01K', 113, 'with_linen', 'high', false, NULL, 'Cleaned', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('103', 'TS1K', 109, 'no_linen', 'normal', false, 'Allergic to flowers', 'InProgress', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('104', 'JS1KT', 62, 'no_linen', 'high', false, NULL, 'InProgress', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('105', 'ST3K', 113, 'no_linen', 'normal', false, NULL, 'Cleaned', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('106', 'ST2K', 40, 'with_linen', 'high', false, NULL, 'InProgress', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('107', 'RO1KY', 88, 'with_linen', 'high', false, 'Late checkout requested', 'Inspected', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('201', 'PS1K', 65, 'no_linen', 'high', false, NULL, 'Inspected', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('202', 'ST3K', 40, 'no_linen', 'high', false, NULL, 'Cleaned', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('203', 'ST3K', 113, 'with_linen', 'normal', false, NULL, 'Cleaned', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('204', 'ST2K', 105, 'no_linen', 'normal', false, NULL, 'Dirty', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('205', 'RO1Q', 65, 'with_linen', 'high', false, NULL, 'Dirty', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('206', 'JS2KT', 53, 'no_linen', 'high', false, NULL, 'Cleaned', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('207', 'JS2KT', 62, 'with_linen', 'high', false, 'Allergic to flowers', 'Cleaned', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;
INSERT INTO public.rooms (room_number, category, credit, linen_status, priority, flagged, special_instructions, house_keeping_status, hotel_id) VALUES ('208', 'TS1K', 73, 'no_linen', 'high', false, NULL, 'InProgress', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1)) ON CONFLICT (hotel_id, room_number) DO UPDATE SET category = EXCLUDED.category, credit = EXCLUDED.credit, linen_status = EXCLUDED.linen_status, priority = EXCLUDED.priority, flagged = EXCLUDED.flagged, special_instructions = EXCLUDED.special_instructions, house_keeping_status = EXCLUDED.house_keeping_status;

-- 2. GUESTS
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Amina Diallo', '3', '365 Garden Rd', 'Orchid Capital', 'amina.diallo.101.arr@palmhavenhotel.com', '1987-01-23', 'https://randomuser.me/api/portraits/women/1.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Amina Diallo' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Noah Fischer', '8', '358 Garden Rd', 'Blue Horizon Group', 'noah.fischer.101.dep@palmhavenhotel.com', '1977-10-24', 'https://randomuser.me/api/portraits/men/38.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Noah Fischer' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Jonas Kim', '5', '928 Garden Ave', 'Palm Haven Trading', 'jonas.kim.102.arr@palmhavenhotel.com', '1980-01-21', 'https://randomuser.me/api/portraits/men/2.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Jonas Kim' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Sofia Dubois', '10', '391 Sunset St', 'Orchid Capital', 'sofia.dubois.103.arr@palmhavenhotel.com', '1981-07-13', 'https://randomuser.me/api/portraits/women/3.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Sofia Dubois' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Daniel Lee', '9', '193 Market Ave', 'Acme Ventures', 'daniel.lee.104.arr@palmhavenhotel.com', '1979-08-01', 'https://randomuser.me/api/portraits/men/4.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Daniel Lee' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Priya Farouk', '3', '978 Palm Blvd', 'Orchid Capital', 'priya.farouk.105.arr@palmhavenhotel.com', '1990-02-28', 'https://randomuser.me/api/portraits/women/5.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Priya Farouk' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Noah Diallo', '1', '41 Ocean Ave', 'Orchid Capital', 'noah.diallo.106.arr@palmhavenhotel.com', '1990-06-28', 'https://randomuser.me/api/portraits/men/6.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Noah Diallo' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Fatima Khalid', '6', '684 Garden St', 'Palm Haven Trading', 'fatima.khalid.106.dep@palmhavenhotel.com', '1976-04-14', 'https://randomuser.me/api/portraits/women/43.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Fatima Khalid' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Emma Kim', '1', '881 Market Ave', 'Palm Haven Trading', 'emma.kim.107.arr@palmhavenhotel.com', '1980-06-27', 'https://randomuser.me/api/portraits/women/7.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Emma Kim' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Lucas Dubois', '10', '525 Garden Ave', 'Sunrise Consulting', 'lucas.dubois.201.arr@palmhavenhotel.com', '1982-04-13', 'https://randomuser.me/api/portraits/men/8.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Lucas Dubois' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Zoe Lee', '4', '533 Sunset Blvd', 'Acme Ventures', 'zoe.lee.202.arr@palmhavenhotel.com', '1977-06-15', 'https://randomuser.me/api/portraits/women/9.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Zoe Lee' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Jordan Farouk', '10', '115 Palm Blvd', 'Acme Ventures', 'jordan.farouk.203.arr@palmhavenhotel.com', '1988-01-15', 'https://randomuser.me/api/portraits/men/10.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Jordan Farouk' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Fatima Diallo', '7', '701 Market Rd', 'Sunrise Consulting', 'fatima.diallo.204.arr@palmhavenhotel.com', '1984-01-13', 'https://randomuser.me/api/portraits/women/11.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Fatima Diallo' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Amina Dubois', '10', '944 Sunset Rd', 'Sunrise Consulting', 'amina.dubois.204.dep@palmhavenhotel.com', '1999-12-15', 'https://randomuser.me/api/portraits/men/48.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Amina Dubois' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Omar Kim', '1', '722 Palm Blvd', 'Orchid Capital', 'omar.kim.205.arr@palmhavenhotel.com', '1977-10-19', 'https://randomuser.me/api/portraits/men/12.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Omar Kim' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Leila Dubois', '2', '208 Market Ave', 'Orchid Capital', 'leila.dubois.206.arr@palmhavenhotel.com', '2000-09-15', 'https://randomuser.me/api/portraits/women/13.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Leila Dubois' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Ivan Lee', '7', '596 Sunset Blvd', 'Sunrise Consulting', 'ivan.lee.207.arr@palmhavenhotel.com', '1981-11-17', 'https://randomuser.me/api/portraits/men/14.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Ivan Lee' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));
INSERT INTO public.guests (full_name, vip_code, address, company, primary_email, dob, image_url, hotel_id) SELECT 'Hannah Farouk', '8', '554 Palm Rd', 'Acme Ventures', 'hannah.farouk.208.arr@palmhavenhotel.com', '1981-08-28', 'https://randomuser.me/api/portraits/women/15.jpg', (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) WHERE NOT EXISTS (SELECT 1 FROM public.guests g WHERE g.full_name = 'Hannah Farouk' AND g.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1));

-- 3. RESERVATIONS
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-03', '2026-01-06', '12:15', 2, 1, 'Due in / Due out', 'Arrival/Departure', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '101' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-03' AND res.departure_date = '2026-01-06' AND res.adults = 2 AND res.kids = 1);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-02', '2026-01-04', NULL, 1, 0, 'Occupied', 'Arrival/Departure', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '101' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-04' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-03', '2026-01-04', '11:30', 2, 1, 'Checked out', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '102' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-03' AND res.departure_date = '2026-01-04' AND res.adults = 2 AND res.kids = 1);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-02', '2026-01-07', '18:00', 1, 0, 'Checked in', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '103' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-07' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-02', '2026-01-08', '11:00', 2, 0, 'Checked in', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '104' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-08' AND res.adults = 2 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-10', '2026-01-14', '11:45', 1, 1, 'Due out', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '105' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-14' AND res.adults = 1 AND res.kids = 1);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-10', '2026-01-16', '16:00', 1, 1, 'Due out', 'Arrival/Departure', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '106' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-16' AND res.adults = 1 AND res.kids = 1);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-08', '2026-01-09', NULL, 1, 0, 'Due in / Due out', 'Arrival/Departure', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '106' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-08' AND res.departure_date = '2026-01-09' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-04', '2026-01-06', '14:00', 2, 0, 'Occupied', 'Stayover', '12:00', r.hotel_id FROM public.rooms r WHERE r.room_number = '107' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-04' AND res.departure_date = '2026-01-06' AND res.adults = 2 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-03', '2026-01-09', NULL, 1, 0, 'Due out', 'Stayover', '13:00', r.hotel_id FROM public.rooms r WHERE r.room_number = '201' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-03' AND res.departure_date = '2026-01-09' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-01', '2026-01-04', NULL, 1, 0, 'Checked out', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '202' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-01' AND res.departure_date = '2026-01-04' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-10', '2026-01-14', '13:45', 1, 0, 'Due in / Due out', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '203' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-14' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-10', '2026-01-15', '13:00', 1, 0, 'Checked out', 'Arrival/Departure', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '204' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-15' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-09', '2026-01-10', NULL, 2, 0, 'Due in / Due out', 'Arrival/Departure', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '204' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-09' AND res.departure_date = '2026-01-10' AND res.adults = 2 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-01', '2026-01-02', '10:30', 1, 1, 'Checked out', 'Stayover', '12:00', r.hotel_id FROM public.rooms r WHERE r.room_number = '205' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-01' AND res.departure_date = '2026-01-02' AND res.adults = 1 AND res.kids = 1);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-07', '2026-01-10', '17:45', 1, 0, 'Checked in', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '206' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-07' AND res.departure_date = '2026-01-10' AND res.adults = 1 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-04', '2026-01-10', '17:30', 2, 0, 'Checked out', 'Stayover', '12:00', r.hotel_id FROM public.rooms r WHERE r.room_number = '207' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-04' AND res.departure_date = '2026-01-10' AND res.adults = 2 AND res.kids = 0);
INSERT INTO public.reservations (room_id, arrival_date, departure_date, eta, adults, kids, reservation_status, front_office_status, promised_time, hotel_id) SELECT r.id, '2026-01-02', '2026-01-06', '10:15', 2, 0, 'Occupied', 'Stayover', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '208' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.reservations res WHERE res.room_id = r.id AND res.hotel_id = r.hotel_id AND res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-06' AND res.adults = 2 AND res.kids = 0);

-- 4. RESERVATION_GUESTS
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '101' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Amina Diallo' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-03' AND res.departure_date = '2026-01-06' AND res.adults = 2 AND res.kids = 1 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '101' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Noah Fischer' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-04' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '102' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Jonas Kim' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-03' AND res.departure_date = '2026-01-04' AND res.adults = 2 AND res.kids = 1 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '103' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Sofia Dubois' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-07' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '104' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Daniel Lee' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-08' AND res.adults = 2 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '105' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Priya Farouk' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-14' AND res.adults = 1 AND res.kids = 1 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '106' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Noah Diallo' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-16' AND res.adults = 1 AND res.kids = 1 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '106' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Fatima Khalid' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-08' AND res.departure_date = '2026-01-09' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '107' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Emma Kim' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-04' AND res.departure_date = '2026-01-06' AND res.adults = 2 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '201' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Lucas Dubois' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-03' AND res.departure_date = '2026-01-09' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '202' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Zoe Lee' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-01' AND res.departure_date = '2026-01-04' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '203' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Jordan Farouk' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-14' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '204' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Fatima Diallo' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-10' AND res.departure_date = '2026-01-15' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '204' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Amina Dubois' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-09' AND res.departure_date = '2026-01-10' AND res.adults = 2 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '205' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Omar Kim' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-01' AND res.departure_date = '2026-01-02' AND res.adults = 1 AND res.kids = 1 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '206' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Leila Dubois' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-07' AND res.departure_date = '2026-01-10' AND res.adults = 1 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '207' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Ivan Lee' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-04' AND res.departure_date = '2026-01-10' AND res.adults = 2 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);
INSERT INTO public.reservation_guests (reservation_id, guest_id, hotel_id) SELECT res.id, g.id, res.hotel_id FROM public.reservations res JOIN public.rooms r ON r.id = res.room_id AND r.room_number = '208' AND r.hotel_id = res.hotel_id JOIN public.guests g ON g.full_name = 'Hannah Farouk' AND g.hotel_id = res.hotel_id WHERE res.arrival_date = '2026-01-02' AND res.departure_date = '2026-01-06' AND res.adults = 2 AND res.kids = 0 AND NOT EXISTS (SELECT 1 FROM public.reservation_guests rg WHERE rg.reservation_id = res.id AND rg.guest_id = g.id);

-- 5. ROOM_NOTES
INSERT INTO public.room_notes (room_id, text, created_by_id, hotel_id) SELECT r.id, 'Check minibar usage', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '105' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.room_notes n WHERE n.room_id = r.id AND n.text = 'Check minibar usage');
INSERT INTO public.room_notes (room_id, text, created_by_id, hotel_id) SELECT r.id, 'Do not move desk items', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '107' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.room_notes n WHERE n.room_id = r.id AND n.text = 'Do not move desk items');
INSERT INTO public.room_notes (room_id, text, created_by_id, hotel_id) SELECT r.id, 'Refill water bottles', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '204' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.room_notes n WHERE n.room_id = r.id AND n.text = 'Refill water bottles');
INSERT INTO public.room_notes (room_id, text, created_by_id, hotel_id) SELECT r.id, 'Extra towels requested', NULL, r.hotel_id FROM public.rooms r WHERE r.room_number = '208' AND r.hotel_id = (SELECT id FROM public.hotels WHERE name = 'Palm Haven Hotel' LIMIT 1) AND NOT EXISTS (SELECT 1 FROM public.room_notes n WHERE n.room_id = r.id AND n.text = 'Extra towels requested');
