/**
 * Canonical permission keys.
 *
 * GENERATED by scripts/generateRbac.js from matrix.json — do not edit by hand.
 * Run `npm run rbac:generate` after changing the matrix.
 *
 * These constants exist for typo-safety at call sites. They are NOT an
 * authority on what a user may do — the caller's real permission set comes
 * from the database via `get_my_permissions()`, and the security boundary is
 * RLS (`auth_has_permission`). Client gating is UX only.
 */

export const PERMISSIONS = {
  // Tab visibility
  /** See the Home (Dashboard) tab */
  HOME_VIEW: 'tab.home.view',
  /** See the Rooms tab */
  ROOMS_VIEW: 'tab.rooms.view',
  /** See the Chat tab */
  CHAT_VIEW: 'tab.chat.view',
  /** See the Tickets tab */
  TICKETS_VIEW: 'tab.tickets.view',
  /** See the Lost & Found tab */
  LOST_AND_FOUND_VIEW: 'tab.lost_and_found.view',
  /** See the Staff tab */
  STAFF_VIEW: 'tab.staff.view',
  /** See the Settings tab */
  SETTINGS_VIEW: 'tab.settings.view',

  // Rooms
  /** Open room lists and room detail */
  ROOMS_READ: 'rooms.read',
  /** Reassign a room to different staff */
  ROOMS_REASSIGN: 'rooms.reassign',
  /** Change a room's housekeeping status */
  ROOMS_STATUS_UPDATE: 'rooms.status.update',
  /** Read room notes */
  ROOMS_NOTES_VIEW: 'rooms.notes.view',
  /** Add a room note */
  ROOMS_NOTES_CREATE: 'rooms.notes.create',
  /** Read guest special instructions */
  ROOMS_SPECIAL_INSTRUCTIONS_VIEW: 'rooms.special_instructions.view',
  /** Open the room History tab */
  ROOMS_HISTORY_VIEW: 'rooms.history.view',
  /** Download a room history report */
  ROOMS_HISTORY_EXPORT: 'rooms.history.export',
  /** Open the room Checklist tab */
  ROOMS_CHECKLIST_VIEW: 'rooms.checklist.view',
  /** Tick off checklist items */
  ROOMS_CHECKLIST_COMPLETE: 'rooms.checklist.complete',
  /** See room credit values */
  ROOMS_CREDITS_VIEW: 'rooms.credits.view',
  /** Bill and adjust room credits */
  ROOMS_CREDITS_MANAGE: 'rooms.credits.manage',
  /** See front-office status on a room */
  ROOMS_FRONT_OFFICE_STATUS_VIEW: 'rooms.front_office_status.view',
  /** See reservation status on a room */
  ROOMS_RESERVATION_STATUS_VIEW: 'rooms.reservation_status.view',
  /** Mark a room as rush / priority */
  ROOMS_RUSH_TOGGLE: 'rooms.rush.toggle',
  /** Flag and unflag a room */
  ROOMS_FLAG_TOGGLE: 'rooms.flag.toggle',

  // Chat
  /** Start a direct chat */
  CHAT_CREATE: 'chat.create',
  /** Create and administer group chats */
  CHAT_GROUPS_MANAGE: 'chat.groups.manage',

  // Tickets
  /** Raise a ticket */
  TICKETS_CREATE: 'tickets.create',
  /** Edit a ticket */
  TICKETS_UPDATE: 'tickets.update',
  /** Close a ticket */
  TICKETS_CLOSE: 'tickets.close',

  // Lost & Found
  /** Browse lost & found items */
  LOST_AND_FOUND_READ: 'lost_and_found.read',
  /** Register a found item */
  LOST_AND_FOUND_REGISTER: 'lost_and_found.register',
  /** Edit and resolve lost & found items */
  LOST_AND_FOUND_MANAGE: 'lost_and_found.manage',

  // Staff
  /** View staff lists and workloads */
  STAFF_READ: 'staff.read',
  /** Assign rooms to staff and edit staff records */
  STAFF_MANAGE: 'staff.manage',

  // Settings
  /** Change hotel-level settings */
  SETTINGS_MANAGE: 'settings.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/** Every permission key, for iteration and validation. */
export const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSIONS);

/**
 * Tab id -> the permission required to see it.
 *
 * Consumed by the bottom tab bar and the More menu. Both must fail CLOSED:
 * a tab id missing from this map is hidden, never shown.
 */
export const TAB_PERMISSION: Record<string, Permission> = {
  Home: PERMISSIONS.HOME_VIEW,
  Rooms: PERMISSIONS.ROOMS_VIEW,
  Chat: PERMISSIONS.CHAT_VIEW,
  Tickets: PERMISSIONS.TICKETS_VIEW,
  LostAndFound: PERMISSIONS.LOST_AND_FOUND_VIEW,
  Staff: PERMISSIONS.STAFF_VIEW,
  Settings: PERMISSIONS.SETTINGS_VIEW,
};

/**
 * Tab order used to resolve a landing route. The first tab whose permission
 * the user holds is where the app opens — so F&B/Kitchen staff, who have no
 * Dashboard right, land on Tickets rather than a screen they cannot see.
 */
export const TAB_ORDER: readonly string[] = [
  'Home',
  'Rooms',
  'Chat',
  'Tickets',
  'LostAndFound',
  'Staff',
  'Settings',
];
