/**
 * Icon registry — every UI icon the app can render.
 *
 * GENERATED by scripts/generateIcons.js from assets/icons/<group>/*.svg.
 * Do not edit by hand — run `npm run icons:generate` instead.
 *
 * To add an icon: export it from Figma, normalise it
 * (`node scripts/normalizeSvg.js <file> --mono <colour>` for single-colour
 * glyphs), drop it in the right group folder, and re-run the generator.
 *
 * Consume via `<Icon name="status-dirty" />` — never require() an icon inside
 * a screen or component.
 */

// actions
import ActionFilter from '@assets/icons/actions/action-filter.svg';
import ActionFlag from '@assets/icons/actions/action-flag.svg';
import ActionSearch from '@assets/icons/actions/action-search.svg';
// nav
import NavChat from '@assets/icons/nav/nav-chat.svg';
import NavHome from '@assets/icons/nav/nav-home.svg';
import NavLostFound from '@assets/icons/nav/nav-lost-found.svg';
import NavStaff from '@assets/icons/nav/nav-staff.svg';
import NavTickets from '@assets/icons/nav/nav-tickets.svg';
// room-status
import StatusCleaned from '@assets/icons/room-status/status-cleaned.svg';
import StatusDirty from '@assets/icons/room-status/status-dirty.svg';
import StatusInProgress from '@assets/icons/room-status/status-in-progress.svg';
import StatusInspected from '@assets/icons/room-status/status-inspected.svg';

export const icons = {
  // actions
  'action-filter': ActionFilter,
  'action-flag': ActionFlag,
  'action-search': ActionSearch,
  // nav
  'nav-chat': NavChat,
  'nav-home': NavHome,
  'nav-lost-found': NavLostFound,
  'nav-staff': NavStaff,
  'nav-tickets': NavTickets,
  // room-status
  'status-cleaned': StatusCleaned,
  'status-dirty': StatusDirty,
  'status-in-progress': StatusInProgress,
  'status-inspected': StatusInspected,
} as const;

export type IconName = keyof typeof icons;

/**
 * width / height for each glyph, from its viewBox.
 *
 * Figma glyphs are rarely square, so <Icon> derives width from height rather
 * than forcing a square box and letterboxing the art at the wrong size.
 */
export const ICON_ASPECT: Record<IconName, number> = {
  'action-filter': 2,
  'action-flag': 1.1833,
  'action-search': 1,
  'nav-chat': 1.0003,
  'nav-home': 1.0744,
  'nav-lost-found': 0.9066,
  'nav-staff': 1.0771,
  'nav-tickets': 0.8567,
  'status-cleaned': 1.0323,
  'status-dirty': 1.1075,
  'status-in-progress': 0.958,
  'status-inspected': 1.1265,
};

/**
 * Icons authored in a single colour, so `<Icon color=…>` tints them.
 * Two-tone brand marks are absent here — recolouring them destroys the mark.
 */
export const TINTABLE_ICONS: ReadonlySet<IconName> = new Set([
  'action-filter',
  'action-flag',
  'action-search',
  'nav-chat',
  'nav-staff',
  'nav-tickets',
  'status-cleaned',
  'status-dirty',
  'status-in-progress',
  'status-inspected',
]);
