export { default as TicketsScreen } from './screens/TicketsScreen';
export { default as CreateTicketScreen } from './screens/CreateTicketScreen';
export { default as SelectTicketLocationScreen } from './screens/SelectTicketLocationScreen';
export { default as CreateTicketFormScreen } from './screens/CreateTicketFormScreen';
export { default as TicketCard } from './components/TicketCard';
export type { TicketStatusAnchorLayout } from './components/TicketCard';
export { default as TicketForm } from './components/TicketForm';
export * from './services/tickets';
export * from './types/tickets.types';
export { DEPARTMENT_NAME_TO_ICON, DEPARTMENT_SLUG_TO_DB_NAME } from '@/lib/departments';
