#!/usr/bin/env node
/**
 * Generate src/global.css from design-system.json.
 *
 *   npm run tokens:generate
 *
 * design-system.json is the single source of truth for design tokens. It was
 * previously hand-mirrored into global.css with a comment asking future editors
 * to keep the two in sync; they did not. By the time this script was written the
 * CSS was missing the entire spacing scale, 7 radii and 3 font sizes, and
 * disagreed with the JSON about the font family.
 *
 * Generating removes the possibility, the same way scripts/generateRbac.js does
 * for roles and permissions.
 *
 * Naming follows Tailwind v4's @theme namespaces, so a token becomes a utility:
 *   --color-status-dirty  -> bg-status-dirty / text-status-dirty
 *   --spacing-lg          -> p-lg / gap-lg / mt-lg
 *   --radius-2xl          -> rounded-2xl
 *   --text-hestia-lg      -> text-hestia-lg
 *
 * Font sizes keep the `hestia-` prefix deliberately. Overriding Tailwind's own
 * --text-sm etc. would silently redefine `text-sm` app-wide and drop the
 * paired line-heights; an explicit prefix is worth the extra characters.
 */

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const SOURCE = path.join(REPO, 'design-system.json');
const OUT = path.join(REPO, 'src/global.css');

const ds = JSON.parse(fs.readFileSync(SOURCE, 'utf8'));

/** `inProgress` -> `in-progress`, `2xl` -> `2xl`. */
const kebab = (key) => key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

/**
 * Colour groups in design-system.json -> the prefix their tokens get.
 *
 * `text` and `background` are renamed on the way out. A token named
 * --color-text-primary produces the utility `text-text-primary`, and
 * --color-bg-card produces `bg-bg-card`; the stutter is tiresome to write and
 * to read. `ink` and `surface` are the usual design-system names for these and
 * give `text-ink-primary` / `bg-surface-card`. The JS side is untouched —
 * `colors.text.primary` still reads from the same JSON.
 */
const COLOR_GROUPS = {
  status: 'status',
  background: 'surface',
  text: 'ink',
  border: 'border',
  badge: 'badge',
};

const lines = [];
const w = (s = '') => lines.push(s);
let tokenCount = 0;

const emit = (name, value) => {
  w(`    ${name}: ${value};`);
  tokenCount += 1;
};

const section = (title) => {
  w();
  w(`    /* ${title} */`);
};

w('/**');
w(' * Hestia design tokens.');
w(' *');
w(' * GENERATED by scripts/generateTokens.js from design-system.json.');
w(' * Do not edit by hand — run `npm run tokens:generate` instead.');
w(' */');
w('@import "tailwindcss/theme.css" layer(theme);');
w('@import "tailwindcss/preflight.css" layer(base);');
w('@import "tailwindcss/utilities.css";');
w();
w('@layer theme {');
w('  @theme {');

// -- colours ----------------------------------------------------------------
section('Brand');
emit('--color-primary', ds.colors.primary.main);
emit('--color-primary-light', ds.colors.primary.light);
emit('--color-primary-dark', ds.colors.primary.dark);

for (const [group, prefix] of Object.entries(COLOR_GROUPS)) {
  const entries = ds.colors[group];
  if (!entries) continue;
  section(`${group.charAt(0).toUpperCase()}${group.slice(1)}`);
  for (const [key, value] of Object.entries(entries)) {
    emit(`--color-${prefix}-${kebab(key)}`, value);
  }
}

// -- spacing ----------------------------------------------------------------
section('Spacing');
for (const [key, value] of Object.entries(ds.spacing ?? {})) {
  emit(`--spacing-${kebab(key)}`, value);
}

// -- radius -----------------------------------------------------------------
section('Radius');
for (const [key, value] of Object.entries(ds.borderRadius ?? {})) {
  emit(`--radius-${kebab(key)}`, value === '0' ? '0px' : value);
}

// -- type -------------------------------------------------------------------
section('Type scale');
for (const [key, value] of Object.entries(ds.typography?.fontSizes ?? {})) {
  emit(`--text-hestia-${kebab(key)}`, value);
}

section('Font families');
w('    /* Helvetica is the design-system face. Android has no Helvetica and');
w('       falls back to Roboto — matching what typography.fontFamily.primary');
w('       already does in the StyleSheet screens. */');
for (const [key, value] of Object.entries(ds.typography?.fontFamily ?? {})) {
  emit(`--font-hestia-${kebab(key)}`, value);
}

// -- shadows ----------------------------------------------------------------
if (ds.colors.shadow) {
  section('Shadows');
  for (const [key, value] of Object.entries(ds.colors.shadow)) {
    emit(`--shadow-${kebab(key)}`, value);
  }
}

w('  }');
w('}');
w();

// Platform font defaults are a react-native-css concern, not a design token —
// they map Tailwind's generic families onto what each OS actually ships.
w('/* Platform font families (react-native-css) — not from design-system.json. */');
w('@media android {');
w('  :root {');
w('    --font-mono: monospace;');
w('    --font-rounded: normal;');
w('    --font-serif: serif;');
w('    --font-sans: normal;');
w('  }');
w('}');
w();
w('@media ios {');
w('  :root {');
w('    --font-mono: ui-monospace;');
w('    --font-serif: ui-serif;');
w('    --font-sans: system-ui;');
w('    --font-rounded: ui-rounded;');
w('  }');
w('}');
w();

fs.writeFileSync(OUT, lines.join('\n'));
console.log(
  `Generated ${path.relative(REPO, OUT)} from ${path.relative(REPO, SOURCE)} — ${tokenCount} tokens`
);
