#!/usr/bin/env node
/**
 * Generate the RBAC artefacts from src/domain/rbac/matrix.json.
 *
 *   npm run rbac:generate
 *
 * Emits:
 *   1. src/domain/rbac/permissions.ts          — typed permission-key constants
 *   2. supabase/migrations/<ts>_rbac_seed.sql  — idempotent seed
 *
 * matrix.json itself comes from the signed-off spec via
 * scripts/rbac/parse-spec.py. Keeping one source and generating both halves is
 * what prevents the class of drift that produced the `IT Manager` /
 * `IT Administrator` mismatch, where the client and the database disagreed on a
 * role's name and the user silently lost every tab but two.
 *
 * Re-running is safe: permissions.ts is overwritten, and the seed migration is
 * written to a fixed filename so it replaces itself rather than accumulating.
 */

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const MATRIX = path.join(REPO, 'src/domain/rbac/matrix.json');
const PERMISSIONS_TS = path.join(REPO, 'src/domain/rbac/permissions.ts');
const SEED_SQL = path.join(REPO, 'supabase/migrations/20260902000100_rbac_seed.sql');

const matrix = JSON.parse(fs.readFileSync(MATRIX, 'utf8'));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** `rooms.notes.create` -> `ROOMS_NOTES_CREATE`; `tab.home.view` -> `HOME_VIEW`. */
function constantName(key) {
  return key.replace(/^tab\./, '').replace(/[.]/g, '_').toUpperCase();
}

/** Single-quoted SQL string literal. */
function sql(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** The permission keys a role grants, flattened from its 18 rights. */
function permissionsForRole(role) {
  const keys = new Set();
  for (const right of matrix.rights) {
    if (!role.rights[right.key]) continue;
    for (const key of right.permissions) keys.add(key);
  }
  if (role.key === 'full_access') {
    for (const key of matrix.adminOnlyPermissions) keys.add(key);
  }
  return [...keys];
}

// ---------------------------------------------------------------------------
// 1. permissions.ts
// ---------------------------------------------------------------------------

function generatePermissionsTs() {
  const tabRights = matrix.rights.filter((r) =>
    r.permissions.some((p) => p.startsWith('tab.'))
  );

  const lines = [];
  const w = (s = '') => lines.push(s);

  w('/**');
  w(' * Canonical permission keys.');
  w(' *');
  w(' * GENERATED by scripts/generateRbac.js from matrix.json — do not edit by hand.');
  w(' * Run `npm run rbac:generate` after changing the matrix.');
  w(' *');
  w(' * These constants exist for typo-safety at call sites. They are NOT an');
  w(" * authority on what a user may do — the caller's real permission set comes");
  w(' * from the database via `get_my_permissions()`, and the security boundary is');
  w(' * RLS (`auth_has_permission`). Client gating is UX only.');
  w(' */');
  w();
  w('export const PERMISSIONS = {');

  // Group by domain so the constant block reads as sections rather than
  // interleaving `tab.*` with everything else in spec order.
  const groupOf = (key) => (key.startsWith('tab.') ? 'tab' : key.split('.')[0]);
  const groups = new Map();
  for (const permission of matrix.permissions) {
    const group = groupOf(permission.key);
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(permission);
  }

  const GROUP_LABELS = {
    tab: 'Tab visibility',
    rooms: 'Rooms',
    chat: 'Chat',
    tickets: 'Tickets',
    lost_and_found: 'Lost & Found',
    staff: 'Staff',
    settings: 'Settings',
  };

  let first = true;
  for (const [group, permissions] of groups) {
    if (!first) w();
    first = false;
    w(`  // ${GROUP_LABELS[group] ?? group}`);
    for (const permission of permissions) {
      w(`  /** ${permission.description} */`);
      w(`  ${constantName(permission.key)}: '${permission.key}',`);
    }
  }

  w('} as const;');
  w();
  w('export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];');
  w();
  w('/** Every permission key, for iteration and validation. */');
  w('export const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSIONS);');
  w();
  w('/**');
  w(' * Tab id -> the permission required to see it.');
  w(' *');
  w(' * Consumed by the bottom tab bar and the More menu. Both must fail CLOSED:');
  w(' * a tab id missing from this map is hidden, never shown.');
  w(' */');
  w('export const TAB_PERMISSION: Record<string, Permission> = {');

  const TAB_IDS = {
    dashboard: 'Home',
    rooms: 'Rooms',
    chat: 'Chat',
    tickets: 'Tickets',
    lostAndFound: 'LostAndFound',
    staff: 'Staff',
    settings: 'Settings',
  };

  for (const right of tabRights) {
    const tabId = TAB_IDS[right.key];
    const tabPermission = right.permissions.find((p) => p.startsWith('tab.'));
    if (!tabId || !tabPermission) continue;
    w(`  ${tabId}: PERMISSIONS.${constantName(tabPermission)},`);
  }

  w('};');
  w();
  w('/**');
  w(' * Tab order used to resolve a landing route. The first tab whose permission');
  w(' * the user holds is where the app opens — so F&B/Kitchen staff, who have no');
  w(' * Dashboard right, land on Tickets rather than a screen they cannot see.');
  w(' */');
  w('export const TAB_ORDER: readonly string[] = [');
  for (const right of tabRights) {
    const tabId = TAB_IDS[right.key];
    if (tabId) w(`  '${tabId}',`);
  }
  w('];');
  w();

  fs.writeFileSync(PERMISSIONS_TS, lines.join('\n'));
  return matrix.permissions.length;
}

// ---------------------------------------------------------------------------
// 2. seed migration
// ---------------------------------------------------------------------------

function generateSeedSql() {
  const lines = [];
  const w = (s = '') => lines.push(s);
  let grantCount = 0;

  const permissionList = matrix.permissions.map((p) => `  ${sql(p.key)}`).join(',\n');

  w('-- RBAC seed: departments, permissions, roles, role_permissions, job_titles.');
  w('--');
  w('-- GENERATED by scripts/generateRbac.js from src/domain/rbac/matrix.json.');
  w('-- Do not edit by hand — run `npm run rbac:generate` instead.');
  w('--');
  w(`-- Source spec: ${matrix.source}`);
  w(`-- ${matrix.jobTitles.length} job titles across ${matrix.departments.length} departments,`);
  w(`-- collapsing to ${matrix.roles.length} distinct permission profiles.`);
  w('--');
  w('-- Idempotent: safe to re-run. Reference data is upserted by key, and');
  w('-- role_permissions is rebuilt from scratch so a revoked grant is actually');
  w('-- removed rather than left behind.');
  w('--');
  w('-- Ordering matters. The legacy vocabulary is retired BEFORE the new rows go');
  w('-- in, because names are unique and some collide (the old per-title role');
  w('-- "Front Office Agent" vs the new profile of the same name). The legacy');
  w('-- user->role assignment is captured first so the backfill still has it.');
  w();
  w('BEGIN;');
  w();

  // -- capture legacy assignment -------------------------------------------
  w('-- 1. Remember who had which legacy role, before we delete those roles.');
  w('CREATE TEMP TABLE legacy_user_roles ON COMMIT DROP AS');
  w('SELECT u.id AS user_id, r.name AS role_name');
  w('  FROM public.users u');
  w('  JOIN public.roles r ON r.id = u.role_id;');
  w();

  // -- retire legacy reference data ----------------------------------------
  w('-- 2. Retire the legacy vocabulary.');
  w('--    The previous seed used different permission names (view_dashboard,');
  w('--    bill_consumption, ...) and one role per job title, none of it read by');
  w('--    any code or policy. Deleting a role cascades its role_permissions and');
  w('--    nulls the deprecated users.role_id.');
  w('DELETE FROM public.roles WHERE key IS NULL;');
  w('DELETE FROM public.permissions WHERE name NOT IN (');
  w(permissionList);
  w(');');
  w();

  // -- departments ---------------------------------------------------------
  w('-- 3. Departments.');
  w('--    Adopt any row that already carries one of our names but no key —');
  w('--    earlier seeds created departments by name only, and name is UNIQUE, so');
  w('--    inserting alongside them would collide.');
  w('UPDATE public.departments d');
  w('   SET key = v.key');
  w('  FROM (VALUES');
  w(
    matrix.departments
      .map((x) => `    (${sql(x.key)}, ${sql(x.name)})`)
      .join(',\n')
  );
  w('  ) AS v(key, name)');
  w(' WHERE d.name = v.name');
  w('   AND d.key IS NULL');
  w('   AND NOT EXISTS (SELECT 1 FROM public.departments o WHERE o.key = v.key);');
  w();
  w('INSERT INTO public.departments (key, name, description) VALUES');
  w(
    matrix.departments
      .map((d) => `  (${sql(d.key)}, ${sql(d.name)}, ${sql(d.description)})`)
      .join(',\n')
  );
  w('ON CONFLICT (key) DO UPDATE');
  w('  SET name = EXCLUDED.name, description = EXCLUDED.description;');
  w();

  // -- permissions ---------------------------------------------------------
  w('-- 4. Permissions.');
  w('INSERT INTO public.permissions (name, description) VALUES');
  w(
    matrix.permissions
      .map((p) => `  (${sql(p.key)}, ${sql(p.description)})`)
      .join(',\n')
  );
  w('ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;');
  w();

  // -- roles ---------------------------------------------------------------
  w('-- 5. Roles — one per distinct permission profile.');
  w('INSERT INTO public.roles (key, name, description) VALUES');
  w(
    matrix.roles
      .map((r, i) => {
        // Comma before the comment — a trailing `--` would swallow it.
        const comma = i < matrix.roles.length - 1 ? ',' : '';
        const titles = `${r.titleCount} title${r.titleCount === 1 ? '' : 's'}`;
        return `  (${sql(r.key)}, ${sql(r.name)}, ${sql(r.description)})${comma}  -- ${titles}`;
      })
      .join('\n')
  );
  w('ON CONFLICT (key) DO UPDATE');
  w('  SET name = EXCLUDED.name, description = EXCLUDED.description;');
  w();

  // -- role_permissions ----------------------------------------------------
  w('-- 6. Role permissions. Rebuilt wholesale so revoked grants disappear.');
  w('DELETE FROM public.role_permissions;');
  w();
  w('INSERT INTO public.role_permissions (role_id, permission_id)');
  w('SELECT r.id, p.id');
  w('  FROM public.roles r');
  w('  JOIN public.permissions p ON TRUE');
  w(' WHERE (r.key, p.name) IN (');

  const pairs = [];
  for (const role of matrix.roles) {
    const keys = permissionsForRole(role);
    grantCount += keys.length;
    for (const key of keys) pairs.push(`  (${sql(role.key)}, ${sql(key)})`);
  }
  w(pairs.join(',\n'));

  w(' )');
  w('ON CONFLICT (role_id, permission_id) DO NOTHING;');
  w();

  // -- job titles ----------------------------------------------------------
  w('-- 7. Job titles. Display identity; permissions come from the role.');
  w('INSERT INTO public.job_titles (key, name, department_id, role_id, home_variant)');
  w('SELECT v.key, v.name, d.id, r.id, v.home_variant');
  w('  FROM (VALUES');
  w(
    matrix.jobTitles
      .map(
        (t) =>
          `    (${sql(t.key)}, ${sql(t.name)}, ${sql(t.department)}, ` +
          `${sql(t.role)}, ${sql(t.homeVariant)})`
      )
      .join(',\n')
  );
  w('  ) AS v(key, name, department_key, role_key, home_variant)');
  w('  JOIN public.departments d ON d.key = v.department_key');
  w('  JOIN public.roles r       ON r.key = v.role_key');
  w('ON CONFLICT (key) DO UPDATE');
  w('  SET name          = EXCLUDED.name,');
  w('      department_id = EXCLUDED.department_id,');
  w('      role_id       = EXCLUDED.role_id,');
  w('      home_variant  = EXCLUDED.home_variant;');
  w();

  // -- backfill ------------------------------------------------------------
  w('-- 8. Give existing users a job title.');
  w('--    Match the legacy role name captured in step 1 against a job title,');
  w('--    ignoring case, punctuation and spacing ("Housekeeping Portier /');
  w('--    Houseman" vs "Housekeeping Porter / Houseman", "Director of Rooms" vs');
  w('--    "Director Of Rooms"). Anything unmatched stays NULL and resolves to no');
  w('--    permissions, which is the correct fail-closed outcome.');
  w('UPDATE public.users u');
  w('   SET job_title_id = jt.id');
  w('  FROM legacy_user_roles l');
  w('  JOIN public.job_titles jt');
  w("    ON regexp_replace(lower(jt.name), '[^a-z0-9]', '', 'g')");
  w("     = regexp_replace(lower(l.role_name),  '[^a-z0-9]', '', 'g')");
  w(' WHERE u.id = l.user_id');
  w('   AND u.job_title_id IS NULL;');
  w();
  w('-- Keep department in step with the assigned title.');
  w('UPDATE public.users u');
  w('   SET department_id = jt.department_id');
  w('  FROM public.job_titles jt');
  w(' WHERE jt.id = u.job_title_id');
  w('   AND u.department_id IS DISTINCT FROM jt.department_id;');
  w();
  w('DO $$');
  w('DECLARE n_unassigned int;');
  w('BEGIN');
  w('  SELECT count(*) INTO n_unassigned FROM public.users WHERE job_title_id IS NULL;');
  w('  IF n_unassigned > 0 THEN');
  w("    RAISE NOTICE '% user(s) have no job title and therefore no permissions. '");
  w("      'Run scripts/seedUsers.js or assign one via the staff admin.', n_unassigned;");
  w('  END IF;');
  w('END $$;');
  w();

  // -- sanity --------------------------------------------------------------
  w('-- 9. Fail the migration if the seed did not land as expected.');
  w('DO $$');
  w('DECLARE n_roles int; n_titles int; n_perms int; n_grants int;');
  w('BEGIN');
  w('  SELECT count(*) INTO n_roles  FROM public.roles;');
  w('  SELECT count(*) INTO n_titles FROM public.job_titles;');
  w('  SELECT count(*) INTO n_perms  FROM public.permissions;');
  w('  SELECT count(*) INTO n_grants FROM public.role_permissions;');
  w(`  IF n_roles  <> ${matrix.roles.length} THEN`);
  w(`    RAISE EXCEPTION 'expected ${matrix.roles.length} roles, found %', n_roles;`);
  w('  END IF;');
  w(`  IF n_titles <> ${matrix.jobTitles.length} THEN`);
  w(`    RAISE EXCEPTION 'expected ${matrix.jobTitles.length} job titles, found %', n_titles;`);
  w('  END IF;');
  w(`  IF n_perms  <> ${matrix.permissions.length} THEN`);
  w(`    RAISE EXCEPTION 'expected ${matrix.permissions.length} permissions, found %', n_perms;`);
  w('  END IF;');
  w(`  IF n_grants <> ${grantCount} THEN`);
  w(`    RAISE EXCEPTION 'expected ${grantCount} role_permissions, found %', n_grants;`);
  w('  END IF;');
  w('END $$;');
  w();
  w('COMMIT;');
  w();

  fs.writeFileSync(SEED_SQL, lines.join('\n'));
  return grantCount;
}

// ---------------------------------------------------------------------------

const permissionCount = generatePermissionsTs();
const grantCount = generateSeedSql();

console.log(`Generated from ${path.relative(REPO, MATRIX)}:`);
console.log(`  ${path.relative(REPO, PERMISSIONS_TS)} — ${permissionCount} permission keys`);
console.log(
  `  ${path.relative(REPO, SEED_SQL)} — ` +
    `${matrix.departments.length} departments, ${matrix.roles.length} roles, ` +
    `${matrix.jobTitles.length} job titles, ${grantCount} grants`
);
