#!/usr/bin/env node
/**
 * Generate src/components/Icon/registry.ts from the SVGs on disk.
 *
 *   npm run icons:generate
 *
 * Adding an icon becomes: export it from Figma, run scripts/normalizeSvg.js,
 * drop it in the right assets/icons/<group>/ folder, re-run this. No hand-edited
 * import list to forget.
 *
 * The registry key is the filename, which already carries its group prefix per
 * assets/README.md — `status-dirty.svg` -> `status-dirty`, `nav-home.svg` ->
 * `nav-home`. The folder groups the files; the prefix keeps names clustered in
 * autocomplete.
 *
 * Aspect ratio is read from each viewBox and emitted alongside. Figma glyphs are
 * rarely square — the filter icon is 28x14, the home mark 32x29.784 — and forcing
 * them into a square box either letterboxes them at the wrong size or, if
 * preserveAspectRatio is stripped without care, distorts them. <Icon> uses these
 * ratios to derive width from height.
 */

const fs = require('fs');
const path = require('path');

const LIST_ONLY = process.argv.includes('--list');

const REPO = path.resolve(__dirname, '..');
const ICONS_DIR = path.join(REPO, 'assets/icons');
const OUT = path.join(REPO, 'src/components/Icon/registry.ts');

/** `status-dirty` -> `StatusDirty` */
const pascal = (name) =>
  name.split(/[-_]/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');

const groups = fs
  .readdirSync(ICONS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

const found = [];
for (const group of groups) {
  const dir = path.join(ICONS_DIR, group);
  for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()) {
    const key = path.basename(file, '.svg');
    const svg = fs.readFileSync(path.join(dir, file), 'utf8');

    const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
    if (!viewBox) {
      console.error(`  SKIP ${group}/${file} — no viewBox`);
      continue;
    }
    const [, , vbW, vbH] = viewBox.trim().split(/\s+/).map(Number);
    if (!vbW || !vbH) {
      console.error(`  SKIP ${group}/${file} — unusable viewBox "${viewBox}"`);
      continue;
    }

    found.push({
      key,
      group,
      file,
      ident: pascal(key),
      aspect: Number((vbW / vbH).toFixed(4)),
      tintable: svg.includes('currentColor'),
    });
  }
}

if (found.length === 0) {
  console.error('No SVGs found under assets/icons/<group>/ — nothing to generate.');
  process.exit(1);
}

const lines = [];
const w = (s = '') => lines.push(s);

w('/**');
w(' * Icon registry — every UI icon the app can render.');
w(' *');
w(' * GENERATED by scripts/generateIcons.js from assets/icons/<group>/*.svg.');
w(' * Do not edit by hand — run `npm run icons:generate` instead.');
w(' *');
w(' * To add an icon: export it from Figma, normalise it');
w(' * (`node scripts/normalizeSvg.js <file> --mono <colour>` for single-colour');
w(' * glyphs), drop it in the right group folder, and re-run the generator.');
w(' *');
w(' * Consume via `<Icon name="status-dirty" />` — never require() an icon inside');
w(' * a screen or component.');
w(' */');
w();

let lastGroup = null;
for (const icon of found) {
  if (icon.group !== lastGroup) {
    w(`// ${icon.group}`);
    lastGroup = icon.group;
  }
  w(`import ${icon.ident} from '@assets/icons/${icon.group}/${icon.file}';`);
}
w();
w('export const icons = {');
lastGroup = null;
for (const icon of found) {
  if (icon.group !== lastGroup) {
    w(`  // ${icon.group}`);
    lastGroup = icon.group;
  }
  w(`  '${icon.key}': ${icon.ident},`);
}
w('} as const;');
w();
w('export type IconName = keyof typeof icons;');
w();
w('/**');
w(' * width / height for each glyph, from its viewBox.');
w(' *');
w(' * Figma glyphs are rarely square, so <Icon> derives width from height rather');
w(' * than forcing a square box and letterboxing the art at the wrong size.');
w(' */');
w('export const ICON_ASPECT: Record<IconName, number> = {');
for (const icon of found) {
  w(`  '${icon.key}': ${icon.aspect},`);
}
w('};');
w();
w('/**');
w(' * Icons authored in a single colour, so `<Icon color=…>` tints them.');
w(' * Two-tone brand marks are absent here — recolouring them destroys the mark.');
w(' */');
w('export const TINTABLE_ICONS: ReadonlySet<IconName> = new Set([');
for (const icon of found.filter((i) => i.tintable)) {
  w(`  '${icon.key}',`);
}
w(']);');
w();

if (!LIST_ONLY) fs.writeFileSync(OUT, lines.join('\n'));

const tintable = found.filter((i) => i.tintable).length;
console.log(
  LIST_ONLY
    ? 'Registered icons — reuse one of these before exporting a new SVG from Figma:'
    : `Generated ${path.relative(REPO, OUT)}`
);
console.log(`  ${found.length} icons across ${groups.length} groups`);
console.log(`  ${tintable} tintable, ${found.length - tintable} two-tone`);
for (const group of groups) {
  const inGroup = found.filter((i) => i.group === group);
  if (inGroup.length) console.log(`    ${group}: ${inGroup.map((i) => i.key).join(', ')}`);
}
