-- RBAC seed: departments, permissions, roles, role_permissions, job_titles.
--
-- GENERATED by scripts/generateRbac.js from src/domain/rbac/matrix.json.
-- Do not edit by hand — run `npm run rbac:generate` instead.
--
-- Source spec: hestia-roles-2026-01-03.pdf
-- 54 job titles across 8 departments,
-- collapsing to 11 distinct permission profiles.
--
-- Idempotent: safe to re-run. Reference data is upserted by key, and
-- role_permissions is rebuilt from scratch so a revoked grant is actually
-- removed rather than left behind.
--
-- Ordering matters. The legacy vocabulary is retired BEFORE the new rows go
-- in, because names are unique and some collide (the old per-title role
-- "Front Office Agent" vs the new profile of the same name). The legacy
-- user->role assignment is captured first so the backfill still has it.

BEGIN;

-- 1. Remember who had which legacy role, before we delete those roles.
CREATE TEMP TABLE legacy_user_roles ON COMMIT DROP AS
SELECT u.id AS user_id, r.name AS role_name
  FROM public.users u
  JOIN public.roles r ON r.id = u.role_id;

-- 2. Retire the legacy vocabulary.
--    The previous seed used different permission names (view_dashboard,
--    bill_consumption, ...) and one role per job title, none of it read by
--    any code or policy. Deleting a role cascades its role_permissions and
--    nulls the deprecated users.role_id.
DELETE FROM public.roles WHERE key IS NULL;
DELETE FROM public.permissions WHERE name NOT IN (
  'tab.home.view',
  'tab.rooms.view',
  'rooms.read',
  'tab.chat.view',
  'chat.create',
  'chat.groups.manage',
  'tab.tickets.view',
  'tickets.create',
  'tickets.update',
  'tab.lost_and_found.view',
  'lost_and_found.read',
  'lost_and_found.register',
  'tab.staff.view',
  'staff.read',
  'tab.settings.view',
  'rooms.reassign',
  'rooms.status.update',
  'rooms.notes.view',
  'rooms.notes.create',
  'rooms.special_instructions.view',
  'rooms.history.view',
  'rooms.history.export',
  'rooms.checklist.view',
  'rooms.checklist.complete',
  'rooms.credits.view',
  'rooms.credits.manage',
  'rooms.front_office_status.view',
  'rooms.reservation_status.view',
  'rooms.rush.toggle',
  'rooms.flag.toggle',
  'staff.manage',
  'settings.manage',
  'tickets.close',
  'lost_and_found.manage'
);

-- 3. Departments.
--    Adopt any row that already carries one of our names but no key —
--    earlier seeds created departments by name only, and name is UNIQUE, so
--    inserting alongside them would collide.
UPDATE public.departments d
   SET key = v.key
  FROM (VALUES
    ('housekeeping', 'Housekeeping'),
    ('front_office', 'Front Office'),
    ('concierge', 'Concierge'),
    ('in_room_dining', 'In Room Dining'),
    ('engineering', 'Engineering'),
    ('it', 'IT'),
    ('executive', 'Executive and Administration'),
    ('food_beverage', 'Food & Beverage / Kitchen')
  ) AS v(key, name)
 WHERE d.name = v.name
   AND d.key IS NULL
   AND NOT EXISTS (SELECT 1 FROM public.departments o WHERE o.key = v.key);

INSERT INTO public.departments (key, name, description) VALUES
  ('housekeeping', 'Housekeeping', 'Room attendants, supervisors and housekeeping leadership'),
  ('front_office', 'Front Office', 'Reception, night audit and guest relations'),
  ('concierge', 'Concierge', 'Concierge, bell desk and valet'),
  ('in_room_dining', 'In Room Dining', 'Room service and in-suite dining'),
  ('engineering', 'Engineering', 'Maintenance, repairs and facility operations'),
  ('it', 'IT', 'Information technology and technical support'),
  ('executive', 'Executive and Administration', 'General management and hotel administration'),
  ('food_beverage', 'Food & Beverage / Kitchen', 'Restaurants, bars, banquets and kitchen brigade')
ON CONFLICT (key) DO UPDATE
  SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 4. Permissions.
INSERT INTO public.permissions (name, description) VALUES
  ('tab.home.view', 'See the Home (Dashboard) tab'),
  ('tab.rooms.view', 'See the Rooms tab'),
  ('rooms.read', 'Open room lists and room detail'),
  ('tab.chat.view', 'See the Chat tab'),
  ('chat.create', 'Start a direct chat'),
  ('chat.groups.manage', 'Create and administer group chats'),
  ('tab.tickets.view', 'See the Tickets tab'),
  ('tickets.create', 'Raise a ticket'),
  ('tickets.update', 'Edit a ticket'),
  ('tab.lost_and_found.view', 'See the Lost & Found tab'),
  ('lost_and_found.read', 'Browse lost & found items'),
  ('lost_and_found.register', 'Register a found item'),
  ('tab.staff.view', 'See the Staff tab'),
  ('staff.read', 'View staff lists and workloads'),
  ('tab.settings.view', 'See the Settings tab'),
  ('rooms.reassign', 'Reassign a room to different staff'),
  ('rooms.status.update', 'Change a room''s housekeeping status'),
  ('rooms.notes.view', 'Read room notes'),
  ('rooms.notes.create', 'Add a room note'),
  ('rooms.special_instructions.view', 'Read guest special instructions'),
  ('rooms.history.view', 'Open the room History tab'),
  ('rooms.history.export', 'Download a room history report'),
  ('rooms.checklist.view', 'Open the room Checklist tab'),
  ('rooms.checklist.complete', 'Tick off checklist items'),
  ('rooms.credits.view', 'See room credit values'),
  ('rooms.credits.manage', 'Bill and adjust room credits'),
  ('rooms.front_office_status.view', 'See front-office status on a room'),
  ('rooms.reservation_status.view', 'See reservation status on a room'),
  ('rooms.rush.toggle', 'Mark a room as rush / priority'),
  ('rooms.flag.toggle', 'Flag and unflag a room'),
  ('staff.manage', 'Assign rooms to staff and edit staff records'),
  ('settings.manage', 'Change hotel-level settings'),
  ('tickets.close', 'Close a ticket'),
  ('lost_and_found.manage', 'Edit and resolve lost & found items')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

-- 5. Roles — one per distinct permission profile.
INSERT INTO public.roles (key, name, description) VALUES
  ('full_access', 'Full Access', 'Every right. Housekeeping leadership and hotel executives.'),  -- 9 titles
  ('hk_room_attendant', 'Room Attendant', 'Cleans rooms: status changes, notes, checklist and history.'),  -- 1 title
  ('hk_houseman', 'Porter / Houseman', 'Support role: rooms, notes and history, no status changes.'),  -- 1 title
  ('hk_laundry', 'Laundry Attendant', 'Linen duties. No chat.'),  -- 1 title
  ('hk_public_area', 'Public Area Attendant', 'Public areas only. No room access.'),  -- 1 title
  ('ops_senior', 'Operations Senior', 'Front Office, Concierge and In-Room Dining leadership.'),  -- 20 titles
  ('fo_agent', 'Front Office Agent', 'Front desk agents and trainees.'),  -- 4 titles
  ('concierge_agent', 'Concierge Agent', 'Concierge, bell desk and valet floor staff.'),  -- 5 titles
  ('ird_service', 'In-Room Dining Service', 'In-room dining order takers and butlers.'),  -- 2 titles
  ('technical', 'Technical', 'Engineering and IT. Ticket-driven.'),  -- 9 titles
  ('fnb_kitchen', 'F&B / Kitchen', 'Chat, tickets and lost & found only.')  -- 1 title
ON CONFLICT (key) DO UPDATE
  SET name = EXCLUDED.name, description = EXCLUDED.description;

-- 6. Role permissions. Rebuilt wholesale so revoked grants disappear.
DELETE FROM public.role_permissions;

INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
  FROM public.roles r
  JOIN public.permissions p ON TRUE
 WHERE (r.key, p.name) IN (
  ('full_access', 'tab.home.view'),
  ('full_access', 'tab.rooms.view'),
  ('full_access', 'rooms.read'),
  ('full_access', 'tab.chat.view'),
  ('full_access', 'chat.create'),
  ('full_access', 'chat.groups.manage'),
  ('full_access', 'tab.tickets.view'),
  ('full_access', 'tickets.create'),
  ('full_access', 'tickets.update'),
  ('full_access', 'tab.lost_and_found.view'),
  ('full_access', 'lost_and_found.read'),
  ('full_access', 'lost_and_found.register'),
  ('full_access', 'tab.staff.view'),
  ('full_access', 'staff.read'),
  ('full_access', 'tab.settings.view'),
  ('full_access', 'rooms.reassign'),
  ('full_access', 'rooms.status.update'),
  ('full_access', 'rooms.notes.view'),
  ('full_access', 'rooms.notes.create'),
  ('full_access', 'rooms.special_instructions.view'),
  ('full_access', 'rooms.history.view'),
  ('full_access', 'rooms.history.export'),
  ('full_access', 'rooms.checklist.view'),
  ('full_access', 'rooms.checklist.complete'),
  ('full_access', 'rooms.credits.view'),
  ('full_access', 'rooms.credits.manage'),
  ('full_access', 'rooms.front_office_status.view'),
  ('full_access', 'rooms.reservation_status.view'),
  ('full_access', 'rooms.rush.toggle'),
  ('full_access', 'rooms.flag.toggle'),
  ('full_access', 'staff.manage'),
  ('full_access', 'settings.manage'),
  ('full_access', 'tickets.close'),
  ('full_access', 'lost_and_found.manage'),
  ('hk_room_attendant', 'tab.rooms.view'),
  ('hk_room_attendant', 'rooms.read'),
  ('hk_room_attendant', 'tab.chat.view'),
  ('hk_room_attendant', 'chat.create'),
  ('hk_room_attendant', 'chat.groups.manage'),
  ('hk_room_attendant', 'tab.tickets.view'),
  ('hk_room_attendant', 'tickets.create'),
  ('hk_room_attendant', 'tickets.update'),
  ('hk_room_attendant', 'tab.lost_and_found.view'),
  ('hk_room_attendant', 'lost_and_found.read'),
  ('hk_room_attendant', 'lost_and_found.register'),
  ('hk_room_attendant', 'tab.settings.view'),
  ('hk_room_attendant', 'rooms.status.update'),
  ('hk_room_attendant', 'rooms.notes.view'),
  ('hk_room_attendant', 'rooms.notes.create'),
  ('hk_room_attendant', 'rooms.history.view'),
  ('hk_room_attendant', 'rooms.history.export'),
  ('hk_room_attendant', 'rooms.checklist.view'),
  ('hk_room_attendant', 'rooms.checklist.complete'),
  ('hk_houseman', 'tab.home.view'),
  ('hk_houseman', 'tab.rooms.view'),
  ('hk_houseman', 'rooms.read'),
  ('hk_houseman', 'tab.chat.view'),
  ('hk_houseman', 'chat.create'),
  ('hk_houseman', 'chat.groups.manage'),
  ('hk_houseman', 'tab.tickets.view'),
  ('hk_houseman', 'tickets.create'),
  ('hk_houseman', 'tickets.update'),
  ('hk_houseman', 'tab.lost_and_found.view'),
  ('hk_houseman', 'lost_and_found.read'),
  ('hk_houseman', 'lost_and_found.register'),
  ('hk_houseman', 'tab.settings.view'),
  ('hk_houseman', 'rooms.notes.view'),
  ('hk_houseman', 'rooms.notes.create'),
  ('hk_houseman', 'rooms.history.view'),
  ('hk_houseman', 'rooms.history.export'),
  ('hk_laundry', 'tab.home.view'),
  ('hk_laundry', 'tab.rooms.view'),
  ('hk_laundry', 'rooms.read'),
  ('hk_laundry', 'tab.tickets.view'),
  ('hk_laundry', 'tickets.create'),
  ('hk_laundry', 'tickets.update'),
  ('hk_laundry', 'tab.lost_and_found.view'),
  ('hk_laundry', 'lost_and_found.read'),
  ('hk_laundry', 'lost_and_found.register'),
  ('hk_laundry', 'tab.settings.view'),
  ('hk_laundry', 'rooms.notes.view'),
  ('hk_laundry', 'rooms.notes.create'),
  ('hk_laundry', 'rooms.history.view'),
  ('hk_laundry', 'rooms.history.export'),
  ('hk_public_area', 'tab.home.view'),
  ('hk_public_area', 'tab.chat.view'),
  ('hk_public_area', 'chat.create'),
  ('hk_public_area', 'chat.groups.manage'),
  ('hk_public_area', 'tab.tickets.view'),
  ('hk_public_area', 'tickets.create'),
  ('hk_public_area', 'tickets.update'),
  ('hk_public_area', 'tab.lost_and_found.view'),
  ('hk_public_area', 'lost_and_found.read'),
  ('hk_public_area', 'lost_and_found.register'),
  ('hk_public_area', 'tab.settings.view'),
  ('ops_senior', 'tab.home.view'),
  ('ops_senior', 'tab.rooms.view'),
  ('ops_senior', 'rooms.read'),
  ('ops_senior', 'tab.chat.view'),
  ('ops_senior', 'chat.create'),
  ('ops_senior', 'chat.groups.manage'),
  ('ops_senior', 'tab.tickets.view'),
  ('ops_senior', 'tickets.create'),
  ('ops_senior', 'tickets.update'),
  ('ops_senior', 'tab.lost_and_found.view'),
  ('ops_senior', 'lost_and_found.read'),
  ('ops_senior', 'lost_and_found.register'),
  ('ops_senior', 'tab.settings.view'),
  ('ops_senior', 'rooms.notes.view'),
  ('ops_senior', 'rooms.notes.create'),
  ('ops_senior', 'rooms.special_instructions.view'),
  ('ops_senior', 'rooms.history.view'),
  ('ops_senior', 'rooms.history.export'),
  ('ops_senior', 'rooms.checklist.view'),
  ('ops_senior', 'rooms.checklist.complete'),
  ('ops_senior', 'rooms.front_office_status.view'),
  ('ops_senior', 'rooms.reservation_status.view'),
  ('ops_senior', 'rooms.rush.toggle'),
  ('ops_senior', 'rooms.flag.toggle'),
  ('fo_agent', 'tab.home.view'),
  ('fo_agent', 'tab.rooms.view'),
  ('fo_agent', 'rooms.read'),
  ('fo_agent', 'tab.chat.view'),
  ('fo_agent', 'chat.create'),
  ('fo_agent', 'chat.groups.manage'),
  ('fo_agent', 'tab.tickets.view'),
  ('fo_agent', 'tickets.create'),
  ('fo_agent', 'tickets.update'),
  ('fo_agent', 'tab.lost_and_found.view'),
  ('fo_agent', 'lost_and_found.read'),
  ('fo_agent', 'lost_and_found.register'),
  ('fo_agent', 'tab.settings.view'),
  ('fo_agent', 'rooms.notes.view'),
  ('fo_agent', 'rooms.notes.create'),
  ('fo_agent', 'rooms.special_instructions.view'),
  ('fo_agent', 'rooms.checklist.view'),
  ('fo_agent', 'rooms.checklist.complete'),
  ('concierge_agent', 'tab.home.view'),
  ('concierge_agent', 'tab.rooms.view'),
  ('concierge_agent', 'rooms.read'),
  ('concierge_agent', 'tab.chat.view'),
  ('concierge_agent', 'chat.create'),
  ('concierge_agent', 'chat.groups.manage'),
  ('concierge_agent', 'tab.tickets.view'),
  ('concierge_agent', 'tickets.create'),
  ('concierge_agent', 'tickets.update'),
  ('concierge_agent', 'tab.lost_and_found.view'),
  ('concierge_agent', 'lost_and_found.read'),
  ('concierge_agent', 'lost_and_found.register'),
  ('concierge_agent', 'tab.settings.view'),
  ('concierge_agent', 'rooms.notes.view'),
  ('concierge_agent', 'rooms.notes.create'),
  ('concierge_agent', 'rooms.special_instructions.view'),
  ('concierge_agent', 'rooms.front_office_status.view'),
  ('concierge_agent', 'rooms.reservation_status.view'),
  ('concierge_agent', 'rooms.rush.toggle'),
  ('concierge_agent', 'rooms.flag.toggle'),
  ('ird_service', 'tab.home.view'),
  ('ird_service', 'tab.rooms.view'),
  ('ird_service', 'rooms.read'),
  ('ird_service', 'tab.chat.view'),
  ('ird_service', 'chat.create'),
  ('ird_service', 'chat.groups.manage'),
  ('ird_service', 'tab.tickets.view'),
  ('ird_service', 'tickets.create'),
  ('ird_service', 'tickets.update'),
  ('ird_service', 'tab.lost_and_found.view'),
  ('ird_service', 'lost_and_found.read'),
  ('ird_service', 'lost_and_found.register'),
  ('ird_service', 'tab.settings.view'),
  ('ird_service', 'rooms.notes.view'),
  ('ird_service', 'rooms.notes.create'),
  ('ird_service', 'rooms.special_instructions.view'),
  ('ird_service', 'rooms.checklist.view'),
  ('ird_service', 'rooms.checklist.complete'),
  ('ird_service', 'rooms.front_office_status.view'),
  ('ird_service', 'rooms.reservation_status.view'),
  ('ird_service', 'rooms.rush.toggle'),
  ('ird_service', 'rooms.flag.toggle'),
  ('technical', 'tab.home.view'),
  ('technical', 'tab.rooms.view'),
  ('technical', 'rooms.read'),
  ('technical', 'tab.chat.view'),
  ('technical', 'chat.create'),
  ('technical', 'chat.groups.manage'),
  ('technical', 'tab.tickets.view'),
  ('technical', 'tickets.create'),
  ('technical', 'tickets.update'),
  ('technical', 'tab.lost_and_found.view'),
  ('technical', 'lost_and_found.read'),
  ('technical', 'lost_and_found.register'),
  ('technical', 'tab.settings.view'),
  ('technical', 'rooms.notes.view'),
  ('technical', 'rooms.notes.create'),
  ('technical', 'rooms.special_instructions.view'),
  ('technical', 'rooms.history.view'),
  ('technical', 'rooms.history.export'),
  ('technical', 'rooms.front_office_status.view'),
  ('technical', 'rooms.reservation_status.view'),
  ('technical', 'rooms.rush.toggle'),
  ('technical', 'rooms.flag.toggle'),
  ('fnb_kitchen', 'tab.chat.view'),
  ('fnb_kitchen', 'chat.create'),
  ('fnb_kitchen', 'chat.groups.manage'),
  ('fnb_kitchen', 'tab.tickets.view'),
  ('fnb_kitchen', 'tickets.create'),
  ('fnb_kitchen', 'tickets.update'),
  ('fnb_kitchen', 'tab.lost_and_found.view'),
  ('fnb_kitchen', 'lost_and_found.read'),
  ('fnb_kitchen', 'lost_and_found.register'),
  ('fnb_kitchen', 'tab.settings.view')
 )
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- 7. Job titles. Display identity; permissions come from the role.
INSERT INTO public.job_titles (key, name, department_id, role_id, home_variant, rooms_variant)
SELECT v.key, v.name, d.id, r.id, v.home_variant, v.rooms_variant
  FROM (VALUES
    ('executive_housekeeper', 'Executive Housekeeper', 'housekeeping', 'full_access', 'default', 'supervisor'),
    ('housekeeping_manager', 'Housekeeping Manager', 'housekeeping', 'full_access', 'default', 'supervisor'),
    ('assistant_housekeeping_manager', 'Assistant Housekeeping Manager', 'housekeeping', 'full_access', 'default', 'supervisor'),
    ('senior_supervisor', 'Senior Supervisor', 'housekeeping', 'full_access', 'default', 'supervisor'),
    ('supervisor', 'Supervisor', 'housekeeping', 'full_access', 'default', 'supervisor'),
    ('coordinator', 'Coordinator', 'housekeeping', 'full_access', 'default', 'supervisor'),
    ('housekeeping_room_attendant', 'Housekeeping Room Attendant', 'housekeeping', 'hk_room_attendant', 'default', 'attendant'),
    ('housekeeping_porter_houseman', 'Housekeeping Porter / Houseman', 'housekeeping', 'hk_houseman', 'hsk_portier', 'default'),
    ('housekeeping_laundry_attendant', 'Housekeeping Laundry Attendant', 'housekeeping', 'hk_laundry', 'default', 'default'),
    ('housekeeping_public_area_attendant', 'Housekeeping Public Area Attendant', 'housekeeping', 'hk_public_area', 'default', 'default'),
    ('director_of_rooms', 'Director Of Rooms', 'front_office', 'ops_senior', 'default', 'default'),
    ('assistant_director_of_rooms', 'Assistant Director Of Rooms', 'front_office', 'ops_senior', 'default', 'default'),
    ('director_of_front_office', 'Director of Front Office', 'front_office', 'ops_senior', 'default', 'default'),
    ('front_office_manager', 'Front Office Manager', 'front_office', 'ops_senior', 'default', 'default'),
    ('assistant_front_office_manager', 'Assistant Front Office Manager', 'front_office', 'ops_senior', 'default', 'default'),
    ('front_office_supervisor', 'Front Office Supervisor', 'front_office', 'ops_senior', 'default', 'default'),
    ('front_office_agent', 'Front Office Agent', 'front_office', 'fo_agent', 'default', 'default'),
    ('front_office_trainee', 'Front Office Trainee', 'front_office', 'fo_agent', 'default', 'default'),
    ('night_manager', 'Night Manager', 'front_office', 'ops_senior', 'default', 'default'),
    ('night_auditor', 'Night Auditor', 'front_office', 'ops_senior', 'default', 'default'),
    ('night_agent', 'Night Agent', 'front_office', 'fo_agent', 'default', 'default'),
    ('guest_relations_manager', 'Guest Relations Manager', 'front_office', 'ops_senior', 'default', 'default'),
    ('guest_relations_supervisor', 'Guest Relations Supervisor', 'front_office', 'ops_senior', 'default', 'default'),
    ('guest_relations_agent', 'Guest Relations Agent', 'front_office', 'fo_agent', 'default', 'default'),
    ('head_concierge', 'Head Concierge', 'concierge', 'ops_senior', 'default', 'default'),
    ('chief_concierge', 'Chief Concierge', 'concierge', 'ops_senior', 'default', 'default'),
    ('concierge_manager', 'Concierge Manager', 'concierge', 'ops_senior', 'default', 'default'),
    ('assistant_concierge_manager', 'Assistant Concierge Manager', 'concierge', 'ops_senior', 'default', 'default'),
    ('concierge_supervisor', 'Concierge Supervisor', 'concierge', 'ops_senior', 'default', 'default'),
    ('concierge_agent', 'Concierge Agent', 'concierge', 'concierge_agent', 'default', 'default'),
    ('bellboy_supervisor', 'Bellboy Supervisor', 'concierge', 'concierge_agent', 'default', 'default'),
    ('bellboy_agent', 'Bellboy Agent', 'concierge', 'concierge_agent', 'default', 'default'),
    ('valet_supervisor', 'Valet Supervisor', 'concierge', 'concierge_agent', 'default', 'default'),
    ('valet_attendant', 'Valet Attendant', 'concierge', 'concierge_agent', 'default', 'default'),
    ('director_of_in_room_dining', 'Director Of In Room Dining', 'in_room_dining', 'ops_senior', 'default', 'default'),
    ('in_room_dining_manager', 'In Room Dining Manager', 'in_room_dining', 'ops_senior', 'default', 'default'),
    ('in_room_dining_assistant_manager', 'In Room Dining Assistant Manager', 'in_room_dining', 'ops_senior', 'default', 'default'),
    ('in_room_dining_supervisor', 'In Room Dining Supervisor', 'in_room_dining', 'ops_senior', 'default', 'default'),
    ('in_room_dining_waiter_waitress', 'In Room Dining Waiter/Waitress', 'in_room_dining', 'ops_senior', 'default', 'default'),
    ('in_room_dining_order_taker', 'In Room Dining Order Taker', 'in_room_dining', 'ird_service', 'default', 'default'),
    ('butler_in_room_dining', 'Butler In Room Dining', 'in_room_dining', 'ird_service', 'default', 'default'),
    ('director_of_engineering', 'Director of Engineering', 'engineering', 'technical', 'engineering', 'default'),
    ('assistant_director_of_engineering', 'Assistant Director Of Engineering', 'engineering', 'technical', 'engineering', 'default'),
    ('engineering_supervisor', 'Engineering Supervisor', 'engineering', 'technical', 'engineering', 'default'),
    ('shift_engineer', 'Shift Engineer', 'engineering', 'technical', 'engineering', 'default'),
    ('director_of_information_technology', 'Director Of Information Technology', 'it', 'technical', 'default', 'default'),
    ('it_manager', 'IT Manager', 'it', 'technical', 'default', 'default'),
    ('assistant_it_manager', 'Assistant IT Manager', 'it', 'technical', 'default', 'default'),
    ('it_supervisor', 'IT Supervisor', 'it', 'technical', 'default', 'default'),
    ('it_agent', 'IT Agent', 'it', 'technical', 'default', 'default'),
    ('general_manager', 'General Manager', 'executive', 'full_access', 'default', 'default'),
    ('hotel_manager', 'Hotel Manager', 'executive', 'full_access', 'default', 'default'),
    ('assistant_to_general_and_hotel_manager', 'Assistant to General & Hotel Manager', 'executive', 'full_access', 'default', 'default'),
    ('fandb_kitchen_staff', 'F&B / Kitchen Staff', 'food_beverage', 'fnb_kitchen', 'default', 'default')
  ) AS v(key, name, department_key, role_key, home_variant, rooms_variant)
  JOIN public.departments d ON d.key = v.department_key
  JOIN public.roles r       ON r.key = v.role_key
ON CONFLICT (key) DO UPDATE
  SET name          = EXCLUDED.name,
      department_id = EXCLUDED.department_id,
      role_id       = EXCLUDED.role_id,
      home_variant  = EXCLUDED.home_variant,
      rooms_variant = EXCLUDED.rooms_variant;

-- 8. Give existing users a job title.
--    Match the legacy role name captured in step 1 against a job title,
--    ignoring case, punctuation and spacing ("Housekeeping Portier /
--    Houseman" vs "Housekeeping Porter / Houseman", "Director of Rooms" vs
--    "Director Of Rooms"). Anything unmatched stays NULL and resolves to no
--    permissions, which is the correct fail-closed outcome.
UPDATE public.users u
   SET job_title_id = jt.id
  FROM legacy_user_roles l
  JOIN public.job_titles jt
    ON regexp_replace(lower(jt.name), '[^a-z0-9]', '', 'g')
     = regexp_replace(lower(l.role_name),  '[^a-z0-9]', '', 'g')
 WHERE u.id = l.user_id
   AND u.job_title_id IS NULL;

-- Keep department in step with the assigned title.
UPDATE public.users u
   SET department_id = jt.department_id
  FROM public.job_titles jt
 WHERE jt.id = u.job_title_id
   AND u.department_id IS DISTINCT FROM jt.department_id;

DO $$
DECLARE n_unassigned int;
BEGIN
  SELECT count(*) INTO n_unassigned FROM public.users WHERE job_title_id IS NULL;
  IF n_unassigned > 0 THEN
    RAISE NOTICE '% user(s) have no job title and therefore no permissions. '
      'Run scripts/seedUsers.js or assign one via the staff admin.', n_unassigned;
  END IF;
END $$;

-- 9. Fail the migration if the seed did not land as expected.
DO $$
DECLARE n_roles int; n_titles int; n_perms int; n_grants int;
BEGIN
  SELECT count(*) INTO n_roles  FROM public.roles;
  SELECT count(*) INTO n_titles FROM public.job_titles;
  SELECT count(*) INTO n_perms  FROM public.permissions;
  SELECT count(*) INTO n_grants FROM public.role_permissions;
  IF n_roles  <> 11 THEN
    RAISE EXCEPTION 'expected 11 roles, found %', n_roles;
  END IF;
  IF n_titles <> 54 THEN
    RAISE EXCEPTION 'expected 54 job titles, found %', n_titles;
  END IF;
  IF n_perms  <> 34 THEN
    RAISE EXCEPTION 'expected 34 permissions, found %', n_perms;
  END IF;
  IF n_grants <> 211 THEN
    RAISE EXCEPTION 'expected 211 role_permissions, found %', n_grants;
  END IF;
END $$;

COMMIT;
